# Generated by Django 4.2.5 on 2023-09-10 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymodel',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='replymodel',
            options={'verbose_name': 'Отклик', 'verbose_name_plural': 'Отклики'},
        ),
        migrations.RenameField(
            model_name='admodel',
            old_name='full_post',
            new_name='full_ad',
        ),
        migrations.RenameField(
            model_name='admodel',
            old_name='preview',
            new_name='short_ad',
        ),
    ]
