# Generated by Django 4.2.5 on 2023-09-10 04:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_board', '0002_alter_categorymodel_options_alter_replymodel_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdModel',
            new_name='Ad',
        ),
        migrations.RenameModel(
            old_name='CategoryModel',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='ReplyModel',
            new_name='Reply',
        ),
    ]
