# Generated by Django 4.2.5 on 2023-09-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_board', '0003_rename_admodel_ad_rename_categorymodel_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='slug',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='Альт.название'),
        ),
    ]
