# Generated by Django 4.2.5 on 2023-09-17 10:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_board', '0006_alter_ad_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='ad',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='ad',
            old_name='full_ad',
            new_name='text_ad',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='short_ad',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='time_update',
        ),
        migrations.AddField(
            model_name='ad',
            name='pictures',
            field=models.ImageField(blank=True, upload_to='images/pictures/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'webp', 'jpeg', 'gif'))], verbose_name='Превью поста'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор отклика'),
        ),
    ]
