# Generated by Django 4.2.5 on 2023-09-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_board', '0007_alter_ad_managers_rename_full_ad_ad_text_ad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='text',
            field=models.TextField(verbose_name='Отклик'),
        ),
    ]
