# Generated by Django 4.2.5 on 2023-09-25 17:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_board', '0010_alter_ad_options_alter_reply_options_alter_ad_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'verbose_name': 'Отклик пользователя', 'verbose_name_plural': 'Отклики пользователей'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='authors',
        ),
        migrations.AlterField(
            model_name='ad',
            name='pictures',
            field=models.ImageField(blank=True, upload_to='images/pictures/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'webp', 'jpeg', 'gif'))], verbose_name='Картинка'),
        ),
    ]
