# Generated by Django 4.2.5 on 2023-09-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_board', '0011_alter_reply_options_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='dislikes',
            field=models.PositiveIntegerField(default=0, verbose_name='Дизлайки'),
        ),
        migrations.AddField(
            model_name='ad',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='Лайки'),
        ),
    ]
