# Generated by Django 4.2.5 on 2023-09-26 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_board', '0013_remove_ad_dislikes_remove_ad_likes_like_dislike'),
    ]

    operations = [
        migrations.AddField(
            model_name='dislike',
            name='value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='like',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
