# Generated by Django 4.2.5 on 2023-09-27 21:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_board', '0014_dislike_value_like_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='video',
            field=models.FileField(blank=True, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('mp4', 'avi', 'mkv', 'mov'))], verbose_name='Видео'),
        ),
    ]
