# Generated by Django 4.2.5 on 2023-09-29 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_board', '0017_ad_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='ad',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='rating',
        ),
        migrations.DeleteModel(
            name='Dislike',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
