# Generated by Django 4.2.5 on 2023-09-29 20:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_board', '0018_remove_like_ad_remove_like_user_remove_ad_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='likes',
            field=models.ManyToManyField(related_name='ad_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
